### ISSUE TITLE
Create CfA Slack channel: bat-knowledge

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/BAT-knowledge-sharing-base#4]
NAC sponsor will create a new Slack channel on cfa.slack.com using the following naming convention: bat-[BAT_NAME] and invite members

**Comment by Jillzey** [comment]
Current channel is #knowledge-sharing

**Comment by jhibbets** [comment]
@tdooner Can you help us update the slack channel knowledge-sharing --> bat-knowledge

**Comment by tdooner** [comment]
@jhibbets Done!
